[supervisord]
nodaemon=true
user=root
autostart=true
autorestart=true

[program:cron]
command=/usr/sbin/cron -f

[program:nginx]
command=nginx -g "daemon off;"

[program:control]
command=python3 /opt/api-control.py
